apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photo-gallery-pvc
spec:
  volumeName: photo-gallery-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi