apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-file-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mail-app
  template:
    metadata:
      labels:
        app: mail-app
    spec:
      containers:
        - name: mail-app
          image: saimonpranta/node-file-demo 
          volumeMounts:
            - mountPath: /app/store
              name: mongo-vol
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: host-pvc
    
---

apiVersion: v1
kind: Service
metadata:
  name: service-mail
spec:
  type: NodePort
  selector:
    app: mail-app
  ports:
    - name: tcp
      port: 3000
      targetPort: 3000
      nodePort: 30000
