apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /d/micple.com/ks8/node-file-demo-20250212T110850Z-001/node-file-demo/store
    type: DirectoryOrCreate
